CheckIn-CheckOut-TayNinh/CheckIn-CheckOut/CheckIn-CheckOut/Controllers/KhaiBaoDiChuyenController.cs
using CheckIn_CheckOut.Models;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CheckIn_CheckOut.Controllers
{
    public class KhaiBaoDiChuyenController : Controller
    {
        String tokenZalo = ConfigurationManager.AppSettings["ToKenkeyZalo"];
        public class Infomation
        {
            public int error { get; set; }
            public string message { get; set; }
            public dataInfo data { get; set; }
        }
        public class dataInfo
        {
            public int user_gender { get; set; }
            public long user_id { get; set; }
            public long user_id_by_app { get; set; }
            public avatars avatars { get; set; }
            public string avatar { get; set; }
            public string display_name { get; set; }
            public int birth_date { get; set; }
            public string shared_info { get; set; }
        }
        public class avatars
        {
            public string avatar120 { get; set; }
            public string avatar240 { get; set; }
        }
        DataConnectDataContext data = new DataConnectDataContext();
        [Route("nhap-thong-tin/{id}")]
        public ActionResult NhapThongTin(int id)
        {
            ViewData["TinhDiChuyen"] = new SelectList(data.TinhThanhs.Where(n => n.IDTinhTrang == 0).OrderBy(n => n.Stt), "IDTinhThanh", "TenTinhThanh");
            ViewData["Huyen"] = new SelectList(data.GetQuanHuyen(72).OrderBy(n => n.IDQuanHuyen), "IDQuanHuyen", "TenQuanHuyen");
            ViewData["ChotKiemDich"] = new SelectList(data.ChotKiemTraVaos.ToList(), "IDChot", "TenChot",id);
            ViewBag.TinhThanh = data.TinhThanhs.Where(n => n.IDTinhTrang == 0).OrderBy(n => n.Stt).ToList();

            return View();
        }
        [HttpPost]
        [Route("nhap-thong-tin/{id}")]
        public ActionResult NhapThongTin(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                //ViewData["Tinh"] = new SelectList(data.TinhThanhs.OrderBy(n => n.Stt), "IDTinhThanh", "TenTinhThanh");
                //ViewData["LoaiDoiTuong"] = new SelectList(data.LoaiDoiTuongs.ToList().OrderBy(n => n.IDLoaiDoiTuong), "IDLoaiDoiTuong", "TenLoai");
                //ViewData["Huyen"] = new SelectList(data.GetQuanHuyen(72).OrderBy(n => n.IDQuanHuyen), "IDQuanHuyen", "TenQuanHuyen");

                var sodienthoai = collection["SoDienThoai"].ToString();
                var hoten = collection["HoTen"];
                var cmnd = collection["CMND"];
                string titleCase = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(hoten.ToLower());
                //tỉnh di chuyển đến bên ngoài tỉnh tây Ninh
                var idtinh = int.Parse(collection["TINH_HIEN_TAI"]);
                var idquan_dichuyen = int.Parse(collection["HUYEN_HIEN_TAI"]);
                var idxa_dichuyen = int.Parse(collection["XA_HIEN_TAI"]);

                var diemden_trongngay = collection["diadiem"];
                var thoigiannhap = collection["ThoiGianNhap"];

                // thông tin id tinh huyen xa ap,  trong tỉnh
                var idxa = 0;
                try
                {
                    idxa = int.Parse(collection["ListDonVi"]);
                }
                catch
                {
                    idxa = 0;
                }
                var idhuyen = 0;
                try
                {
                    idhuyen = int.Parse(collection["Huyen"]);
                }
                catch
                {
                    idhuyen = 0;
                }
                var idap = 0;
                try
                {
                    idap = int.Parse(collection["AP_HIEN_TAI"]);
                }
                catch
                {

                }
                var diachi = collection["DiaChi"];
                var oaid = collection["OAID"];
                var iddiemkiemdich = int.Parse(collection["ChotKiemDich"]);

                //khai hộ
                //var khaiho = collection["khaiho"];
                // mac định khai hộ bằng 1/
                var khaiho = 1;
                string hanhdongkhai = "[KHAI HỘ] ";
                Boolean tempValue = collection["khaiho"] != null ? true : false;
                if (tempValue == true)
                {
                    khaiho = 1;
                    hanhdongkhai = "[KHAI HỘ] ";
                }
                var loaikhaibao = int.Parse(collection["LoaiLT"]);
                string mucdich = "";
                //Loai =0 la di trong ngya
                //Loai ==1 luu tru lau ngay
                if (loaikhaibao == 0)
                {
                    mucdich = "Mục đích khai báo: Di chuyển trong ngày!";
                    //data.Ins_KhaiBao_ThemLoai(iddiemkiemdich, sodienthoai, DateTime.Now, "KB", khaiho, titleCase, null, idxa, null, oaid, idtinh, diachi,idhuyen, loaikhaibao,null);
                    //data.Ins_KhaiBao_ThemLoaiV2(iddiemkiemdich, sodienthoai, DateTime.Now, "KB", khaiho, titleCase, cmnd, idxa, null, oaid, idtinh, diemden_trongngay, idhuyen, loaikhaibao, null, idquan_dichuyen, idxa_dichuyen);
                    data.Ins_KhaiBao_V3(iddiemkiemdich, sodienthoai, DateTime.Now, "KB", khaiho, titleCase, cmnd, idxa, null, oaid, idtinh, diemden_trongngay, idhuyen, loaikhaibao, null, idquan_dichuyen, idxa_dichuyen, thoigiannhap,"NhapTaiChot",null,null,null,null);
                }
                else
                {
                    mucdich = "Mục đích khai báo: Về nơi cư trú !";
                    //data.Ins_KhaiBao_ThemLoai(iddiemkiemdich, sodienthoai, DateTime.Now, "KB", khaiho, titleCase, null, idxa, null, oaid, idtinh, diachi, null, loaikhaibao, null);
                    data.Ins_KhaiBao_ThemLoaiV2(iddiemkiemdich, sodienthoai, DateTime.Now, "KB", khaiho, titleCase, cmnd, idxa, null, oaid, idtinh, diachi, null, loaikhaibao, idap, idquan_dichuyen, idxa_dichuyen);
                    data.Ins_KhaiBao_V3(iddiemkiemdich, sodienthoai, DateTime.Now, "KB", khaiho, titleCase, cmnd, idxa, null, oaid, idtinh, diachi, null, loaikhaibao, idap, idquan_dichuyen, idxa_dichuyen,thoigiannhap, "NhapTaiChot", null, null, null, null);
                    //data.Ins_KhaiBao(iddiemkiemdich, sodienthoai, DateTime.Now, "KB", 0, titleCase, null, idxa, null, oaid, idtinh,diachi);
                }


                // inset to khai y tế

                var cau1 = int.Parse(collection["Cau1"]);
                var cau2 = int.Parse(collection["Cau2"]);
                var cau3 = int.Parse(collection["Cau3"]);
                var cau4 = int.Parse(collection["Cau4"]);
                data.Ins_ToKhaiYTe(titleCase, sodienthoai, cau1, cau2, cau3, cau4, iddiemkiemdich, null, null, khaiho, "DANGKY");

                //Gửi thông tin cho cán bộ y tế nếu có người khai báo có

                //lấy danh sach thong tin người kiem dich

                //gửi Thong báo nếu có người khai báo có



                //Get thong tin thong báo
                var ttTinh = data.TinhThanhs.SingleOrDefault(n => n.IDTinhThanh == idtinh);
                var ttXa = data.XaPhuongs.SingleOrDefault(n => n.IdXaPhuong == idxa);
                var tthuyen = data.QuanHuyens.SingleOrDefault(n => n.IDQuanHuyen == idhuyen);
                var ttchot = data.ChotKiemTraVaos.SingleOrDefault(n => n.IDChot == iddiemkiemdich);
                //Tính gio
                //var khoangcach = GetDistance(double.Parse(ttXa.QuanHuyen.Longitude), double.Parse(ttXa.QuanHuyen.Latitude), double.Parse(ttchot.Longitude), double.Parse(ttchot.Latitude));

                TinhGioDiChuyen getGio = new TinhGioDiChuyen();
                List<PhuTrachDiaBan> dsphutrach = new List<PhuTrachDiaBan>();

                // tạo biến để chek gửi mess trng ngày
                int trongngay = 0;

                //Loai =0 la di trong ngya
                //Loai ==1 luu tru lau ngay
                if (loaikhaibao == 0)
                {
                    trongngay = 0;
                    getGio = data.TinhGioDiChuyens.FirstOrDefault(n => n.idchot == iddiemkiemdich & n.idhuyen == idhuyen);
                    dsphutrach = data.PhuTrachDiaBans.Where(n => n.IDHuyen == idhuyen && n.ThongBao == true).ToList();
                }
                else
                {
                    trongngay = 1;
                    getGio = data.TinhGioDiChuyens.FirstOrDefault(n => n.idchot == iddiemkiemdich & n.idhuyen == ttXa.QuanHuyen.IDQuanHuyen);
                    dsphutrach = data.PhuTrachDiaBans.Where(n => n.IDXa == idxa & n.ThongBao == true).ToList();
                    var chekidhuyen = data.XaPhuongs.SingleOrDefault(n => n.IdXaPhuong == idxa).IDQuanHuyen;
                    var dshuyen = data.PhuTrachDiaBans.Where(n => n.IDHuyen == chekidhuyen & n.ThongBao == true).ToList();
                    dsphutrach = dsphutrach.Concat(dshuyen).ToList();
                }


                TimeSpan ts = TimeSpan.FromMinutes(double.Parse(getGio.giodichuyen.ToString()));
                //TimeSpan ts = TimeSpan.FromMinutes(180);
                var hours = ts.Hours;
                var minutes = ts.Minutes;
                string gio = "0";
                if (hours > 0)
                {
                    gio = String.Format("{0} giờ {1} phút", hours, minutes);
                }
                else
                {
                    gio = String.Format("{0} phút", minutes);
                }
                var ngay = DateTime.Now.AddMinutes(double.Parse(getGio.giodichuyen.ToString())).ToString("dd/MM/yyyy", CultureInfo.InvariantCulture);

CheckIn-CheckOut-TayNinh/CheckIn-CheckOut/CheckIn-CheckOut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CheckIn-CheckOut-TayNinh/CheckIn-CheckOut/CheckIn-CheckOut/Views/Shared/_LayoutCheck.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet">

</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Trang chủ</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("DanhSachNguoiCheckIn","Home")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Danh sách hành khách</span>
                </a>
            </li>
            <!-- Heading -->
            @*<div class="sidebar-heading">
            Interface
        </div>*@

            <!-- Nav Item - Pages Collapse Menu -->
            @*<li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-fw fa-cog"></i>
                <span>Components</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Custom Components:</h6>
                    <a class="collapse-item" href="buttons.html">Buttons</a>
                    <a class="collapse-item" href="cards.html">Cards</a>
                </div>
            </div>
        </li>*@

            @*Nav Item - Utilities Collapse Menu
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
               aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-fw fa-wrench"></i>
                <span>Utilities</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                 data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Custom Utilities:</h6>
                    <a class="collapse-item" href="utilities-color.html">Colors</a>
                    <a class="collapse-item" href="utilities-border.html">Borders</a>
                    <a class="collapse-item" href="utilities-animation.html">Animations</a>
                    <a class="collapse-item" href="utilities-other.html">Other</a>
                </div>
            </div>
        </li>*@

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Thông tin
            </div>

            @*Nav Item - Pages Collapse Menu
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
               aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-fw fa-folder"></i>
                <span>Pages</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Login Screens:</h6>
                    <a class="collapse-item" href="login.html">Login</a>
                    <a class="collapse-item" href="register.html">Register</a>
                    <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                    <div class="collapse-divider"></div>
                    <h6 class="collapse-header">Other Pages:</h6>
                    <a class="collapse-item" href="404.html">404 Page</a>
                    <a class="collapse-item" href="blank.html">Blank Page</a>
                </div>
            </div>
        </li>

         Nav Item - Charts
        <li class="nav-item">
            <a class="nav-link" href="charts.html">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Charts</span>
            </a>
        </li>*@

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("DanhSaDanhSachSoDienThoai","Home")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Phân quyền</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("DanhSachDiemKiemDich","Home")">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Đơn vị</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="~/Content/img/undraw_rocket.svg" alt="...">
                <p class="text-center mb-2"><strong>ĐĂNG KÝ ĐIỂM CHECK IN</strong></p>
                @Html.ActionLink("Tạo điểm check in", "TaoDiemCheck", "Home", new { @class = "btn btn-success btn-sm" })
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                    @Html.Action("Header","Home")
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()



                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Thoát tài khoản???</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Chọn "Đăng xuất" bên dưới nếu bạn đã sẵn sàng kết thúc phiên hiện tại của mình.
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                    @Html.ActionLink("Đăng xuất", "Logout", "Home", new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Content/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/js/demo/chart-area-demo.js"></script>
    <script src="~/Content/js/demo/chart-pie-demo.js"></script>

</body>
@*<body>
    <div>
        @RenderBody()
    </div>
</body>*@
</html>

CheckIn-CheckOut-TayNinh/CheckIn-CheckOut/CheckIn-CheckOut/Views/Shared/_LayoutPageKhaiBao.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet">

</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()



                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>
                            BCĐ phòng chống dịch Covid-19 Tây Ninh ( Ver: @Html.Action("Ver","KhaiBaoDiChuyen"))
                        </span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/js/sb-admin-2.min.js"></script>

</body>
</html>